services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pki-2fa-app
    ports:
      - "8081:8080"   # Host 8081 â†’ Container 8080
    volumes:
      - seed-data:/data
      - cron-output:/cron
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro
    environment:
      - TZ=UTC
    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
